import Head from 'next/head'
import logo from '../styles/images/logo.png';

export default function Home() {
  return (
    <div id='mainPage'>
      <Head>
        <title>Inkmorphism - the AI Website Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <a href='/' id='logo'>
            <img src="/favicon.ico"/>
            <a>Inkmorphism</a>
        </a>
        <a href='/login'>Sign In</a>
        {/* <img src={profile_pic} alt="Profile Pic"/> */}
      </nav>

      <main>
        <h1>Inkmorphism - the AI Website Builder</h1>
      </main>

      <footer>

      </footer>
    </div>
  )
}
