import Head from 'next/head'
import logo from '../styles/images/logo.png';
import {FaTwitter,FaLinkedin,FaInstagram} from 'react-icons/fa'

export default function Home() {
  return (
    <div id='mainPage'>
      <Head>
        <title>Inkmorphism - the AI Website Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <a href='/' id='logo'>
            <img src="/favicon.ico"/>
            <a>Inkmorphism</a>
        </a>
        <a href='/login'>Sign In</a>
        {/* <img src={profile_pic} alt="Profile Pic"/> */}
      </nav>

      <main>
        <section id='hero'>
          <div id='heroTxt'>
            <h1>Inkmorphism - the AI Website Builder</h1>
            <h2>Get started with a free website</h2>
            <button>Let's go</button>
          </div>
          <img src='main/example.png'/>
        </section>

        <section>
        </section>

        <section>
        </section>

        <section>
        </section>

        <section>
        </section>

        <section>
        </section>

        <section>
        </section>

      </main>

      <footer>
        <div id='socialLinks'>
          <a href='https://twitter.com/inkmorphism'>< FaTwitter /></a>
          <a href='https://instagram.com/inkmorphism'>< FaInstagram /></a>
          <a>< FaLinkedin /></a>
        </div>
      </footer>
    </div>
  )
}
