import Head from 'next/head'
import { useState } from 'react'
import { FaTwitter, FaLinkedin, FaInstagram } from 'react-icons/fa'
import { getAuth } from "firebase/auth";
import app from "../firebase/clientApp";
import { useRouter } from "next/router";

export default function Home() {

  const [mobileToggle, setMobileToggle] = useState("");
  function mobileSwitch() {
    if (mobileToggle === "") {
      setMobileToggle("clicked")
    } else {
      setMobileToggle("")
    }
  }

  let router = useRouter();
  function redirect() {
    setTimeout(() => {
      router.push('/dashboard')
    }, 500)
  }

  function checkLogin() {
    const auth = getAuth(app)
    setTimeout(() => {
      if (auth.currentUser !== null) {
        setTimeout(() => {
          router.push('/dashboard')
        }, 500)
      } else {
        setTimeout(() => {
          router.push('/login')
        }, 500)
      }
    }, 1000)
  }

  return (
    <div id='mainPage'>
      <Head>
        <title>Inkmorphism - the AI Website Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/faviconWh.ico" />
      </Head>
      <nav>
        <a href='/' id='logo' className='noSelect'>
            <img src="/logoWh.png"/>
            <p>Inkmorphism</p>
        </a>
        <div>
          <a className='noSelect' href='/templates'>Templates</a>
          <a>About us</a>
          <a href='/blog'>Blog</a>
          <a onClick={checkLogin}>Sign in</a>
          {/* <img src={profile_pic} alt="Profile Pic"/> */}
        </div>
        <div id='mobileMenu' onClick={mobileSwitch} className={"noSelect " + mobileToggle}>
          <div id='bar1'></div>
          <div id='bar2'></div>
          <div id='bar3'></div>
        </div>
        <div id='overlayMenu' className={mobileToggle}>
          <a className='noSelect' href='/templates'>Templates</a>
          <a className='noSelect'>About us</a>
          <a className='noSelect' href='/blog'>Blog</a>
          <a className='noSelect' onClick={checkLogin}>Sign in</a>
        </div>
      </nav>

      <main>
        <section id='hero'>
          <div id='heroTxt'>
            <h1>Never start with a blank webpage again.</h1>
            <h2>Let Inkmorphism build it for you</h2>
            <a href='/templates'>Let's go</a>
          </div>
          <div id='exampleSites'>
            <img src='main/example1.png'/>
            <img src='main/example2.png'/>
            <img src='main/example4.png'/>
          </div>
        </section>

        <section id='partners'>
          <a className='noSelect' href='https://openai.com/'>
            <img src='main/openaiLogo.png'/>
          </a>
          <div></div>
          <p>We work with</p>
          <div></div>
          <a className='noSelect' href='https://www.midjourney.com'>
            <img src='main/midjourneyLogo.png'/>
          </a>
        </section>

        <section>
        </section>

        <section>
        </section>

        <section>
        </section>

        <section>
        </section>

        <section>
        </section>

      </main>

      <footer>
        <p>Inkmorphism © 2023</p>
        <div id='socialLinks'>
          <a href='https://twitter.com/inkmorphism'>< FaTwitter /></a>
          <a href='https://instagram.com/inkmorphism'>< FaInstagram /></a>
          <a>< FaLinkedin /></a>
        </div>
      </footer>
    </div>
  )
}
